---
- name: Clone Tourplaner Git repo
  ansible.builtin.git:
    repo: https://github.com/DavidJohannesS/tourplaner.git
    dest: "{{ role_path }}/files/gitrepo"
    version: meow
    force: yes

- name: Compile backend
  ansible.builtin.shell: |
    cd "{{ role_path }}/files/gitrepo/backend/springboot"
    chmod +x mvnw
    ./mvnw clean package -DskipTests

- name: Compile Frontent
  ansible.builtin.shell: |
    cd "{{ role_path }}/files/gitrepo/frontend"
    npm install 
    npm run build

