---
- name: Execute SQL script to create tables
  community.postgresql.postgresql_query:
    db: "{{ postgres_db }}"
    port: "{{ postgres_port }}"
    login_user: "{{ postgres_user }}"
    login_password: "{{ postgres_pwd }}"
    host: "{{ ansible_host }}"
    query: "{{ lookup('file', '{{ role_path }}/files/tables.sql') }}"

