---
# tasks file for postgres
- name: Setup
  ansible.builtin.include_tasks: setup.yml

- name: Remove/Reset
  ansible.builtin.include_tasks: utils.yml
  tags:
    - utils
    - never

- name: Compile stuff
  ansible.builtin.include_tasks: compile.yml

- name: Setup backend
  ansible.builtin.include_tasks: springboot.yml

- name: Start nginx
  ansible.builtin.include_tasks: nginx.yml

