---
- name: Setup MTCG Postgres DB
  tags:
    - setup
    - reset
  block:
    - name: Create app network
      community.docker.docker_network:
        name: tourplaner_net
        state: present

    - name: Pull img
      community.docker.docker_image:
        name: "{{ postgres_img }}"
        tag: "{{ postgres_ver }}"
        source: pull

    - name: Ensure volume exists
      community.docker.docker_volume:
        name: "{{ postgres_volume }}"
        state: present
    - debug:
        msg: "{{ postgres_volume }}:/var/lib/postgresql/data"

    - name: Start container
      community.docker.docker_container:
        name: "{{ postgres_container }}"
        image: "{{ postgres_img }}"
        state: started
        published_ports:
          - "{{ postgres_port }}:5432"
        volumes:
          - source: "{{ postgres_volume }}"
            target: /var/lib/postgresql/data
            type: volume
        env:
          POSTGRES_USER: "{{ postgres_user }}"
          POSTGRES_PASSWORD: "{{ postgres_pwd }}"
          POSTGRES_DB: "{{ postgres_db }}"
        networks:
          - name: tourplaner_net

