---
- name: Setup backend container
  tags:
    - setup
  block:
    - name: Pull img
      community.docker.docker_image:
        name: "{{ springboot_img }}"
        tag: "{{ springboot_ver }}"
        source: pull

    - name: Start container
      community.docker.docker_container:
        name: "{{ springboot_container }}"
        image: "{{ springboot_img }}:{{ springboot_ver }}"
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "{{ springboot_port }}:8080"
        volumes:
          - "{{ springboot_dir }}:/srv"
          - "{{ role_path }}/files/entrypoint.sh:/entrypoint.sh:ro"
        command: "bash /entrypoint.sh"
        networks:
          - name: tourplaner_net
